name: livesino

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies & run
        run: |
          cd ./src
          dotnet restore
          dotnet run ${{ BotToken }}
      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: "[Auto] update"
